// if you're using panel, carefully edit this part.

const sessionName = 'session';

// Hardcoded session string
const session = `eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEs5bFYzdFdCdGFrOWRtWTRMdmkvTXpNd25aQVFoZmRGVmx3RU5OTERrZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTGJhOEVEQW8vaitNSVBBOG1DdGxaK2lPMjYzQ0ErcmRsV04wcUt4Rm9BZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPQkErYTdEcmUzVEZ4cnZwYk5vYkVXdW9rRzZBS1VNUVRSL2xXTnpZVjBNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFeC9qNXJmQy9NTUdGS1k2aVlsRWFrNmZ6QVYwa296SVNsaWZrZEVOZGlFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IllKUFpDY1ppdHpzNHFUQVQ4REE1ZVJYTDY5L2NTa0pyaXhLOWZCa21JRnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldIQ3Z3RUx4K2k2S1RyWEMxa2pIcVFWcnliL3lVUlVUM2VhdlpsMUlXUjA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicUxxQVp2cXRvL2czWmlFREtSdms1WDMraFRFcjZXZEcwSEtJUjV2cUNIRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaU9PaHlrUUs4YWoxeEFtY3hURVNFT0psdU1rZUswQ1hVa25KTW1paThpaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZYUWI2NmlXQXdnRkVMc05rM25PQXJqOGJvTzY2Y29VN0hKS2Vndm1tQXJ2OGZEeHlHZmpTTFpub01DdlM4RzdvdG5rM2h4WHQ2OU9jOEVNZ0dtRGlRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA4LCJhZHZTZWNyZXRLZXkiOiJGcWpqNmE2c0xvYmZwTHZuRnRrOHZ4Qm1SMmR6eHVFRWg0ZlJabWE5ejFZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0MTgxOTU4MkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIyMzVCN0ZDM0M3NkM1MzgxNDZCRDZDRUE1MUVEMjM3MiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU0MDczMTE4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NDE4MTk1ODJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNjg0OEYxNEIzMzIwQ0Q4RjI4MkQ4QkNDMDNFN0IwNUYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDA3MzExOX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiTU5OMkhYUDciLCJtZSI6eyJpZCI6IjI1NDc0MTgxOTU4MjoyM0BzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZW08J2WmPCdlo3wnZaG8J2WlvCdlbTwnZaH8J2Wl/CdlobwnZaN8J2WjvCdlpIiLCJsaWQiOiI4MDE3NDc1ODU0NzU2NjoyM0BsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xLc21Vb1FpcEMweEFZWUFTQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ik9MZXVXL0RyVkxQS0Y0R3haMUU3ZVFXbHFGOXFmY1lDaEF4ZlEyc21vUmM9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjNJNFMvZkgvSlA5UXI5YkQwRU5uSWJFV3JSZ1pQRmprUWdnNjZOVldQRE41ZE44TWJLN3haZ1ZrSC9uYnF5cTM1eWlYTU5teFFvS1IxOCt2MVV6b0NBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJDMVNHbHFRQXN3SW1YWU1RUUZDem53V0VQb2xjNEM4bGJ4MFM0UW44cHZFYkI0S3hpZjNEK0VuMk1weUNVNVArQmZXWGt3cWpUTXVKZEtScUN6SVhnZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc0MTgxOTU4MjoyM0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJUaTNybHZ3NjFTenloZUJzV2RSTzNrRnBhaGZhbjNHQW9RTVgwTnJKcUVYIn19XSwicGxhdGZvcm0iOiJzbWJhIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQTBJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTQwNzMxMTEsImxhc3RQcm9wSGFzaCI6IlBXazVCIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFIN2YifQ==`;

const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗥𝗔𝗩𝗘𝗡';
const dev = process.env.DEV || '254114660061';
const owner = dev.split(',');
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/duv8ac.jpg';
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};