// if you're using panel, carefully edit this part.

const sessionName = 'session';

// Hardcoded session string
const session = `eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUVxNTh2WDVPKzJ4Mk9YaG9aTlpXTEpsdDkyN1pZVUVQUkNjUlhZT0FuUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUtxcTRML0g1ODdsTHNLUENQV0dScFhpWVgrRDQyNXFFWUpreEs4d1JVZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjTTZyYk9ieHhaY1JnVVdLdGhOeGYrTGRVOFdHOWo3STJXSEtIeXRmdkY4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1bVlpODlIRnRMNS9pMFVHMlUrS095VVNFdnJUMHhlcFdTbGpWSUpxempNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBCTzVyOVdtRVhOSlhxS0I5SWkwa0F6NjIyYUNEaHVHdjZRU3FlbVJzRW89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1hT1Bvem9LTzJtcGJqcnN3NWo3OXEwQ1A2c2UxNTltMDZ5MnJNMlNQVWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0RSQzFuR281NEQreVh6UjFDOHAyYXhxMGZ3Z1JjeEVVaEFoR05BbnlWST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0JpUUd0OVhSYzFXbTNMUkJFc09YRkRDNjhPRDBoUGlOMnB0WFhZSlFtUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtIanlZbUR0RU9ScUtJRkFzOFBxMXltbUpkZlk4TUpIV3I1WWdWamxHVUZyZWdLU2Z2RnBoRUI4Tk5HT3J3S29uWVNncHJidVAwNmZzNEZ1ck51YWlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NiwiYWR2U2VjcmV0S2V5IjoieFZybXFEeTB3SDFJR205YlA0WHdvaElZWDVxU0ZHdVE3TDFHMnVjcTNlWT0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOlt7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NDE4MTk1ODJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQkE1QkNCNjE0OUI1NkJGMDM2QzUzREEwRkJBRUEyMEIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDI0MTc4OX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQxODE5NTgyQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjFBRUI4MEY4NEY0QkMyNTkwNTBGMUNDMjMyNTkyRTlCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQyNDE3ODl9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkxTSzdHWllEIiwibWUiOnsiaWQiOiIyNTQ3NDE4MTk1ODI6MjVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2VtPCdlpjwnZaN8J2WhvCdlpbwnZW08J2Wh/CdlpfwnZaG8J2WjfCdlo7wnZaSIiwibGlkIjoiODAxNzQ3NTg1NDc1NjY6MjVAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMT3NtVW9RNkxXK3hBWVlBaUFBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJPTGV1Vy9EclZMUEtGNEd4WjFFN2VRV2xxRjlxZmNZQ2hBeGZRMnNtb1JjPSIsImFjY291bnRTaWduYXR1cmUiOiJlYld1TXlxbmgyNTg5a0pTSEhZMUJrUFUrU1paWmd2TlowWTBiMW5TOWNRNy9qNnI3bDMyR3VjRXdCeW9HbUliYlRiQ2ZjSVdXTEZGZmpHV1Z0eG5CQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoidjZxQ29DRWptSlZhVlA0b0FDZnVQclR2NEd1V1MvSXJqMytNWElnanlqSmtuUEI1em91d2d5cVFsbWl2akoxWUd0akRRU1RnYjY1K21HaHp5WXluaXc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NDE4MTk1ODI6MjVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVGkzcmx2dzYxU3p5aGVCc1dkUk8za0ZwYWhmYW4zR0FvUU1YME5ySnFFWCJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU0MjQxNzgxLCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSDdlIn0=`;

const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗥𝗔𝗩𝗘𝗡';
const dev = process.env.DEV || '254114660061';
const owner = dev.split(',');
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/duv8ac.jpg';
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};