// if you're using panel, carefully edit this part.

const sessionName = 'session';

// Hardcoded session string
const session = `eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0Yzc1FnUm9BNDJZTHkxUDhOSTlmQndQaUZTbHlvYXZtVlcrNFhTaHpsST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiclBHckRYeFdyZk1KdHd0UHNtSjhwb0Z5cVJBVEpzbmZqT1BNRGJ0aG1sbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLTUxtUGhlM3QxTkNXejBEdW02c25XYXJQOU9GL3VKNjV3S0t4dEx0OEdNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtU1ZFeko2RUVyYWp4ZTc3OVF1c29xVjA4NGR4NXhjNERrd1BSWUxmRVJZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtHbEEyalVYRHdmUE1rWmN3aUNKc2hrYVlKWFBmRHZuSmpibStpS1ZVVkE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InRGK0I1MTBkUHZuaS9xcVI2aFBYUVpyN2Y5QmJaWTRnTWgrU1Nsc3Zta1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUJZb1AxdDVlNDVhemdDZW95ZUNuUHh2RVZJNFNmWWhGL2FTb3lmcHBVST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaE5wWmVDRTVpTXFGcHl4SFAvSmZMVVpGdnNnNWRnZFROc2JBR0pNL05Bcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZrcEFuRWJjZldGaDJJQ2RjejdvVWw2YitZRXBONlU2Nmw5Z0Fnc0w4MGNJSkMxSmczTENpR3JUYVVFcnRuc0RQYVp1VGFvc3pLeXFSZWNoRkhVcWlRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTksImFkdlNlY3JldEtleSI6IjFNdHNtU1R6MFh2L2paTG80V0sva3psU1FXN3NNR3krZXFrbHN2T2JBYnM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQxODE5NTgyQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjBEQUNDQjFGRkRDRTk3MzczQUFFOEY2MTU1NzU2Rjc0In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQxMzkxOTF9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0MTgxOTU4MkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzODc5MDAxNkEyQkU1NTAzQjBFNDYzMUUxQTk0MUI3NiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU0MTM5MTkxfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI4R1EyOTlOOSIsIm1lIjp7ImlkIjoiMjU0NzQxODE5NTgyOjI0QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdlbTwnZaY8J2WjfCdlobwnZaW8J2VtPCdlofwnZaX8J2WhvCdlo3wnZaO8J2WkiIsImxpZCI6IjgwMTc0NzU4NTQ3NTY2OjI0QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTE9zbVVvUW81UzR4QVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiT0xldVcvRHJWTFBLRjRHeFoxRTdlUVdscUY5cWZjWUNoQXhmUTJzbW9SYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiY2JKRWczSllJaVRtRWNYMG93UWZLcDZlSVZxbC9FR0RCQ29VMkgyZGZueFR6QnEzdHk0NnFMVEEyZURHRXNzODRiMG5xVC9zYkIzZE9jbmMwc2ZtQUE9PSIsImRldmljZVNpZ25hdHVyZSI6IlZ2emUwVjF1cVZGcUpFNDRwWlNTOGd3cUN1cFVGeHA3K0Y3ckZCcnBaNW4yNUc0YmtvTWJWZnl4UHJwME5GQ1VxZGtrTmdRTlVnQWNVbjlpa2pLa2pnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzQxODE5NTgyOjI0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlRpM3Jsdnc2MVN6eWhlQnNXZFJPM2tGcGFoZmFuM0dBb1FNWDBOckpxRVgifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBMElDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1NDEzOTE4NSwibGFzdFByb3BIYXNoIjoiUFdrNUIiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUg3aCJ9`;

const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗥𝗔𝗩𝗘𝗡';
const dev = process.env.DEV || '254114660061';
const owner = dev.split(',');
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/duv8ac.jpg';
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};